name: 배포

on:
  push:
    branches: ["main"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: 의존성 설치
        run: npm install
      - name: 빌드
        run: |
          npm run build
          ls -la build || echo "Build directory not found"
      - name: 도커허브에 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PW }}
      - name: 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-front .
      - name: 도커허브에 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-front
      - name: AWS EC2에 ssh 접속 후 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_IP }}
          port: 22
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo timedatectl set-timezone Asia/Seoul
            export PATH=$PATH:/usr/local/bin:/usr/bin
            docker pull ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}-front
            docker compose -f /home/ubuntu/docker-compose.yml down
            docker volume prune -f
            docker compose -f /home/ubuntu/docker-compose.yml up -d --force-recreate